### ISSUE TITLE
Just hearing a short sound instead of the local mp3-file

### ISSUE THREAD

**Issue by FrankP2** [orcema/node-red-contrib-google-home-notifier-offline#1]
Hi orcema,

i appreciate the work you have done, especially being most of the time offline.

Unfortunately the main thing does not work: my Google Home Mini just plays a short sound instead of the mp3-file, which i get from translate.google.com and stored on my raspi in \tmp\ghcache\.

The Google Home Mini is just two days old and was automatically updated. Maybe the latest update has changed the api?

My nodes:
[{"id":"bfa7d1b7.677b3","type":"inject","z":"7bfcfddd.bba1a4","name":"","topic":"","payload":"Hallo zusammen","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":630,"y":160,"wires":[["575a1a6d.fcf984"]]},{"id":"575a1a6d.fcf984","type":"change","z":"7bfcfddd.bba1a4","name":"","rules":[{"t":"set","p":"emitVolume","pt":"msg","to":"50","tot":"str"},{"t":"set","p":"cacheFolder","pt":"msg","to":"/tmp/ghcache","tot":"str"},{"t":"set","p":"fileServerPort","pt":"msg","to":"8081","tot":"str"},{"t":"set","p":"payload","pt":"msg","to":"Hallo ihr","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":830,"y":160,"wires":[["b696c39b.972dc","f9878064.5ac748"]]},{"id":"f9878064.5ac748","type":"googlehome-notifier-offline","z":"7bfcfddd.bba1a4","server":"6225c7fd.483ee8","name":"","x":1100,"y":110,"wires":[]},{"id":"b696c39b.972dc","type":"debug","z":"7bfcfddd.bba1a4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1030,"y":200,"wires":[]},{"id":"6225c7fd.483ee8","type":"googlehome-config-node-offline","z":"","ipaddress":"192.168.178.48","name":"","language":"de"}]

The directory of the raspi with the download mp3-files:
pi@raspberrypi:/tmp/ghcache $ ls -l
insgesamt 20
-rw-r--r-- 1 pi pi 3936 Jun 10 16:33 HALLO_IHR.mp3
-rw-r--r-- 1 pi pi 5952 Jun 10 16:18 HALLO_ZUSAMMEN.mp3
-rw-r--r-- 1 pi pi 4800 Jun 10 15:40 HELLO_WORLD.mp3

**Comment by FrankP2** [comment]
Ok, i found something: the internet access of Google Home Mini was blocked. 
 - Internet access granted: the googlehome-notifier-offline node works fine
 - Internet access blocked: the Google Home Mini just plays a short sound (like "du-du-uh")

Though, i thought the idea of the offline-notifier node includes the possibility for Google Home Mini to be offline. Am i wrong?

**Comment by orcema** [comment]
Hi, you are right, no internet connection is needed for messages already
played, but if the message is new then an internet connection is needed for
the creation of the audio sound.
If you experience a different behavior please let me know.
Regards

**Comment by orcema** [comment]
the internet connection is not needed by google home mini but by the rpi

**Comment by orcema** [comment]
You are right, without internet connection streaming to the googleHome is impossible.
I tried streaming an mp3 song to the googleHome using the google-home-notifier-offline and the whole traffic was uploaded to the google servers instead streaming straight to the google home device on the local network.
Google-home-notifier-offline uses the library "castv2" for streaming to the googleHome device.
 
The basic idea for google-home-notifier-offline was to store the mp3 files for already played notifications on a local server in order to avoid to depend on googleTTS for each new notification.
Finally this finding  makes me think i have to find an alternative way for notification for security purposes.
