### ISSUE TITLE
Only english

### ISSUE THREAD

**Issue by soulanda** [orcema/node-red-contrib-google-home-notifier-offline#10]
I would like to see other language options, not just English.
regards

**Comment by orcema** [comment]
There are already all the available languages from google translate as you can see on the figure here below.


![image](https://user-images.githubusercontent.com/12600222/90099463-d6cfb680-dd3a-11ea-8f32-874d72835cf2.png)

The point is when you create the node for the first time you have only the english language. 

![image](https://user-images.githubusercontent.com/12600222/90099864-b6542c00-dd3b-11ea-999f-97b212677330.png)

So create the node with the english language, close the configuration editor and then reopen it and you will see all the available languages.
