### ISSUE TITLE
Impossible to change the language

### ISSUE THREAD

**Issue by Arnaudd78000** [orcema/node-red-contrib-google-home-notifier-offline#11]
Great job. That's work very fine but in english and I'm french... In the configuration, only english language is available. Any idea ??

**Comment by orcema** [comment]
Bonjour,

Il s'agit d'un problème déjà abordé sous point [https://github.com/orcema/node-red-contrib-google-home-notifier-offline/issues/10](url)
En fait lors de la création du noeu il n'y a que la langue anglaise qui est disponible, mais il suffit de l'editer à nouveau suite à la création et à ce moment apparaissent toutes les langues.

**Comment by Arnaudd78000** [comment]
Bonjour,

J'ai bien suivi l'explication issue 10 mais rien n'y fait. Je ne vois que
la langue anglaise de disponible.
Je pose un noeud GoogleHome-Notifer-Offline. Je l'édite et ajoute un noeud
(langue anglaise). Je ferme la fenêtre. J'ouvre à nouveau. Toujours que la
langue anglaise de disponible...
Bizarre.

Le dim. 15 nov. 2020 à 22:24, Orce MARINKOVSKI <notifications@github.com> a
écrit :
