### ISSUE TITLE
"Please select a non-Default language" error

### ISSUE THREAD

**Issue by denisjoshua** [orcema/node-red-contrib-google-home-notifier-offline#14]
Hi there, 
I just installed node-red-google-notify 1.3.5
but when I test it it give me the error: Please select a non-Default language

When I try to set the language in the node it don't let me cause the language field is empty:
![image](https://user-images.githubusercontent.com/32936800/122901754-2107c800-d34e-11eb-8525-36d7181cce6a.png)

Thanks a lot 
Denis

**Comment by orcema** [comment]
I have difficulties to find the origin of this issue as you can check in the discussion here:

https://community.home-assistant.io/t/tts-queue-in-node-red-for-google-cloud-and-other-tts-engine/214022/33

What device is running your node-red? Do you access node-red by http or https ?
Do you have any errors in log files?

**Comment by denisjoshua** [comment]
I run Node-Red inside of Home Assistance
but it's like it not found the language list.
Thanks again

Il giorno mar 22 giu 2021 alle ore 14:14 Orce MARINKOVSKI <
***@***.***> ha scritto:

**Comment by orcema** [comment]
Sorry i didn't see you try to use a replaced node. 
It has been replaced by https://flows.nodered.org/node/node-red-google-notify

**Comment by denisjoshua** [comment]
I just updated to the 1.4.1 version. 
But I have same problem... the language values from a drop-down menu, is missing:
![image](https://user-images.githubusercontent.com/32936800/123209124-7532b980-d4c0-11eb-8407-a9284ab91e6e.png)

I take same error: 
![image](https://user-images.githubusercontent.com/32936800/123209170-85e32f80-d4c0-11eb-9a04-9f5be6872072.png)

Thanks again
Denis

**Comment by orcema** [comment]
As you run the node-red add-on you have to install the node according to this issue https://github.com/hassio-addons/addon-node-red/issues/1052

**Comment by denisjoshua** [comment]
I have ask help on the https://github.com/hassio-addons/addon-node-red/issues/1052 page
Thanks a lot again
Denis

**Comment by orcema** [comment]
read me updated with the install instrucitons on hassio

https://github.com/orcema/node-red-google-notify

**Comment by denisjoshua** [comment]
Hi there 
I can confirm that I update (from the palette) to 1.4.2 version 
and now it's wonderful work :-) 
![image](https://user-images.githubusercontent.com/32936800/123367435-36613a00-d57a-11eb-9205-e10631ee00bf.png)


Thanks a lot 
Denis
