### ISSUE TITLE
Request - send to more than 1 google-home device

### ISSUE THREAD

**Issue by Smith754** [orcema/node-red-contrib-google-home-notifier-offline#2]
Love this node! Works great.  

But I have 6 google-home devices and it is a little difficult to try and broadcast to them using this node because it only takes 1 IP address at a time. 
If I try to run 6 nodes in parallel it often times jams or lags a little. But then isn't it loading the same file 6 times? Yikes. 

We just need a way to broadcast to all google-home devices. I can do this with media_player in Home Assistant.

**Comment by orcema** [comment]
I my configuration i managed to create a template flow like the one here below.
This way i can define within the message flow the destination for the message.
If you want to try out copy the code below and import it in node-red from clipboard.
Open the flow template and define once all your google devices.

The node acts as a file-server and requests the destination devices to connect to it and to play the mp3 message. If you experience lags, then try to insert a different delay sending the message for each google device defined in the template flow.

> [{"id":"e243ca9f.709d78","type":"subflow","name":"GoogleHomeNotification","info":"","in":[{"x":50,"y":30,"wires":[{"id":"e0408923.b2b4e8"}]}],"out":[]},{"id":"add7f181.cbd7a","type":"switch","z":"e243ca9f.709d78","name":"GoogleNotifyDestination","property":"destination","propertyType":"msg","rules":[{"t":"eq","v":"living","vt":"str"},{"t":"eq","v":"bureau","vt":"str"},{"t":"eq","v":"all","vt":"str"}],"checkall":"true","repair":false,"outputs":3,"x":450,"y":260,"wires":[["56b5faea.be0234"],["273c31b9.9552ae"],["56b5faea.be0234","273c31b9.9552ae"]],"outputLabels":["Google Home","Google Home mini",""]},{"id":"56b5faea.be0234","type":"googlehome-notifier-offline","z":"e243ca9f.709d78","server":"e303565c.9a86c8","name":"Google Home","x":800,"y":180,"wires":[]},{"id":"273c31b9.9552ae","type":"googlehome-notifier-offline","z":"e243ca9f.709d78","server":"8e684684.9c2ae8","name":"Google Home Mini","x":810,"y":320,"wires":[]},{"id":"e0408923.b2b4e8","type":"change","z":"e243ca9f.709d78","name":"","rules":[{"t":"set","p":"cacheFolder","pt":"msg","to":"/config/GHCache","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":200,"y":260,"wires":[["add7f181.cbd7a"]]},{"id":"e303565c.9a86c8","type":"googlehome-config-node-offline","z":"e243ca9f.709d78","ipaddress":"xxx.xxx.xxx.xxx","name":"Google Home","language":"en"},{"id":"8e684684.9c2ae8","type":"googlehome-config-node-offline","z":"e243ca9f.709d78","ipaddress":"xxx.xxx.xxx.xxx","name":"Google Home Mini","language":"en"},{"id":"943330a7.0ba44","type":"subflow:e243ca9f.709d78","z":"678992b.4e98d6c","name":"","x":510,"y":240,"wires":[]}]

**Comment by Smith754** [comment]
That is just awesome!  Some really nice programming too!  Wow.  It just simplified my whole TTS routine to almost nothing. Thank you so much!  All the home automation people are going to love it.

I had to add "emitVolume" and "destination" to the change-node in the subflow.  I couldn't seem to figure out how to add those in the main node with the environment variables. They just wouldn't pass through that I could see.  No mind.  It all works fine for what I'm doing.

Also, it does seem to be more zippy!  less lag. Kudo's! 

I think some of my lag issues have to do with hass.io (a type of Home Assistant) because it also happens with other nodes dealing with sound, not just this one. It is a known issue. There is a setting to "delay attempts" or not on the server setting.  But it's a little wonky either way. Sometimes it will miss a call, other times be delayed. It's just hass.io.  Perhaps they'll fix that in the future.
