### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by SergioRius** [orcema/node-red-contrib-google-home-notifier-offline#3]
It doesn't work.
The version with volume adjustment, also doesn't work, but the google home emits the dot sound as when adjusts the volume.
Removing the node and using the sample flow/node on the standard node-red-contrib-google-home-notify works as expected.

**Comment by orcema** [comment]
could it be you face the same problem as here https://github.com/orcema/node-red-contrib-google-home-notifier-offline/issues/1 ?
