### ISSUE TITLE
Speech playback slow

### ISSUE THREAD

**Issue by Paulf007** [orcema/node-red-contrib-google-home-notifier-offline#6]
Can there be or is there an option to increase the speech speed of google TTS similar to the 
google-tts node?

**Comment by orcema** [comment]
currently there is no such option, but  i will try to include it soon

**Comment by Paulf007** [comment]
That will be super , thank you!! Well done one the plugin as it is as well!

**Comment by orcema** [comment]
version 1.1 will be available starting from tomorrow. The reading speed can be set with "msg.speed"

**Comment by Paulf007** [comment]
Have tested the node for Two days and is working well, thank you!

**Comment by orcema** [comment]
the final working version is 0.1.5
