### ISSUE TITLE
emitVolume ignored for MP3 files

### ISSUE THREAD

**Issue by ghost** [orcema/node-red-contrib-google-home-notifier-offline#7]
Hi,

Is there a reason why the emitVolume is not being set when playing an MP3 file?
Looks like line 101 is missing the setVolume.

If this is intended, then i'll create a fork.
If not, any idea when you could fix this?
thanks,
Simon

https://github.com/orcema/node-red-contrib-google-home-notifier-offline/blob/cd77ed2121644f6d800300a620c4a9e4db62e6f7/node-red-google-home-notifier-offline.js#L101

**Comment by orcema** [comment]
the property "setVolume" has to be set on the "msg". You should be able to set the play volume for each message.
Soon i will implement default values that will be set via config.
