### ISSUE TITLE
wrong file name for MP3

### ISSUE THREAD

**Issue by ichbaum** [orcema/node-red-contrib-google-home-notifier-offline#8]
Hi,
my google home mini will not play any text because its safed under a wrong name. The mp3 file has a "-1" added to the end.

The payload:
{"_msgid":"7ade3213.a11eec","topic":"","payload":"This is a test","cacheFolder":"/tmp"}

The filename: 
-rw-r--r-- 1 pi   pi   6432 Jun 15 08:24 THIS_IS_A_TEST-1.mp3

**Comment by orcema** [comment]
this ending number "-1" represents the speak speed. Make sure you have the latest version e.g. version 0.1.5
this issue appeared on previous versions.
